---
version: '3.5'
services:
 zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
     - "2888:2888"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2888
      ZOOKEEPER_TICK_TIME: 2000

 broker:
    image: confluentinc/cp-server
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2888'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

 orderproducer:
    image: orderproducer_image
    hostname: "orderproducer"
    container_name: orderproducer
    depends_on:
      - broker
    ports:
     - "5000:80"
    deploy:
        resources:
            limits:
              cpus: '2.0'
              memory: 512M
            reservations:
              cpus: '2.0'
              memory: 512M  
  
 orderconsumer:
    image: orderconsumer_image
    hostname: "orderconsumer"
    container_name: orderconsumer
    depends_on:
      - broker
    deploy:
        resources:
            limits:
              cpus: '1.0'
              memory: 128M
            reservations:
              cpus: '1.0'
              memory: 128M  
          
